version: '2.3'
services:

  cards:
    image: cards:v1
    restart: "no"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
    expose:
      - 8080
    ports:
      - "8080:8080"

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
