version: '2.3'
services:

  cards:
    image: cards:v1
    container_name: cards
    restart: "no"
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_SCHEMA: public
    expose:
      - 8080
    ports:
      - "8080:8080"

  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/schema:/docker-entrypoint-initdb.d/
